production:
    # parent production in molecules/s
    base_q: 1.e+28

parent:
    name: "H2O"
    # outflow velocity of parent, km/s
    v_outflow: 0.85
    # # total lifetime of parent molecule, seconds
    # tau_T: 86000
    T_to_d_ratio: 0.93
    # dissociative lifetime of molecule, seconds
    tau_d: 50000
    # approximate cross section for most molecules we care about, cm^2
    sigma: 3.0e-16

fragment:
    name: "OH"
    # velocity of fragment, km/s
    v_photo: 1.05
    # total lifetime of fragment molecule, seconds
    tau_T: 500000

position:
    # distance in AU
    d_heliocentric: 1.0
    # adjustments to apply to input data
    transform_method: "festou_fortran"

# python version parameters
grid:
    radial_points: 150
    angular_points: 60
    radial_substeps: 50

# for python results
printing:
    print_progress: True
    print_time_dependence: False
    print_radial_density: False
    print_column_density: False
    show_fragment_agreement_check: True
    show_aperture_checks: True

# for python results
plotting:
    show_radial_plots: False
    show_column_density_plots: False
    show_3d_column_density_centered: False
    show_3d_column_density_off_center: False

# Other info
misc:
    comet_name: "prod_dep_test"
    # comet-earth distance in AU
    delta: 1.0
    # fluorescence factor
    gfactor: 2.33e-4

fortran_version:
    vmodel_binary: 'bin/fvm'
    out_file: 'fort.16'
    in_file: 'fparam.dat'
