production:
    type: "binned"
    # rates of production, in molecules/s
    rates:
        - 1.e+28
        - 3.e+29
    # times these productions started, in days ago
    times_at_productions:
        - 30
        - 15

parent:
    name: "H2O"
    # outflow velocity of parent, km/s
    v: 0.85
    # total lifetime of parent molecule, seconds
    tau_T: 86430
    # dissociative lifetime of molecule, seconds
    tau_d: 101730
    # approximate cross section for most molecules we care about, cm^2
    sigma: 3.0e-16

fragment:
    name: "OH"
    # velocity of fragment, km/s
    v: 1.05
    # total lifetime of fragment molecule, seconds
    tau_T: 129000

# Model parameters
grid:
    radial_points: 50
    angular_points: 30
    radial_substeps: 12  # can probably leave this alone
    angular_substeps: 7  # this one too

printing:
    print_progress: True

    print_radial_density: False
    print_column_density: False

    show_agreement_check: True
    show_aperture_checks: True

plotting:
    show_radial_plots: False
    show_column_density_plots: False
    show_3d_column_density_centered: True
    show_3d_column_density_off_center: True
