production:
  # parent production in molecules/s
  base_q: 1.e+28

  # time_variation_type: "gaussian"
  # params:
  #   # amplitude in molecules/s
  #   amplitude: 3.e30
  #   # std_dev in hours
  #   std_dev: 20.0
  #   # time at peak in hours ago
  #   t_max: 24.0

  # time_variation_type: "sine wave"
  # params:
  #   # amplitude in molecules/s
  #   amplitude: 3.e28
  #   # period in hours
  #   period: 20.0
  #   # delta, angular offset in hours
  #   delta: 3.0

  # time_variation_type: "square pulse"
  # params:
  #   # amplitude in molecules/s
  #   amplitude: 4.e30
  #   # duration in hours
  #   duration: 5.0
  #   # start of pulse, in hours ago
  #   t_start: 20.0

parent:
  # outflow velocity of parent, km/s
  v_outflow: 0.85
  # ratio between total and dissociative lifetimes
  tau_T: 80000
  # dissociative lifetime of molecule, seconds
  tau_d: 86000
  # approximate cross section for most molecules we care about, cm^2
  sigma: 3.0e-16

fragment:
  # velocity of fragment, km/s
  v_photo: 1.05
  # total lifetime of fragment molecule, seconds
  tau_T: 160000

grid:
  radial_points: 150
  angular_points: 80
  radial_substeps: 80
  parent_destruction_level: 0.95
  fragment_destruction_level: 0.99
